format_version: 10
pipelines:
  prometheus:
    group: tools
    display_order: -1
    materials:
      ansible:
        git: https://github.com/Sumanth990/miscellaneous-code.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - apply:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            apply:
              timeout: 0
              tasks:
                - exec:
#terraform init
                    command: terraform
                    arguments: ["init"]
                - exec:
#terraform apply -auto-approve
                    command: terraform
                    arguments: [ "apply", "-auto-approve" ]
