format_version: 10
pipelines:
  prometheus-ansible:
    group: tools
    display_order: -1
    materials:
      ansible:
        git: https://github.com/Sumanth990/miscellaneous-code.git
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
      - apply:
          fetch_materials: true
          approval:
            type: manual
          jobs:
            apply:
              timeout: 0
              tasks:
                - exec:
                    #terraform init
                    command: bash
                    arguments: [ "ansible.sh" ]
                    working_directory: prometheus
